
version: '3.8'

networks:
  mysql-net:
    name: mysql-net

volumes:
  mysql-vol: {}

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:?Variable not set}
      # - MYSQL_USER=${DB_USERNAME:?Variable not set}
      - MYSQL_PASSWORD=${DB_PASSWORD:?Variable not set}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?Variable not set}
    networks:
      - mysql-net
    ports:
      - ${DB_PORT:-3306}:3306
    restart: unless-stopped
    volumes:
      - mysql-vol:/var/lib/mysql
    healthcheck:
      test: MYSQL_PWD=$$DB_ROOT_PASSWORD mysqladmin -h `hostname -i` -P 3306 -u root --silent ping
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    depends_on:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=flat
      - ADMINER_PLUGINS=dump-zip
    ports:
      - ${ADMINER_PORT:-8080}:8080
    networks:
      - mysql-net
    restart: unless-stopped
